### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by catg0tfish** [zhuss/vue-pages#1]
> Starting dev server...

 ERROR  Failed to compile with 2 errors                                                                         13:50:53

 error  in ./src/pages/index/index_main.js

Module build failed: Error: Cannot find module 'babel-runtime/core-js/get-iterator'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\work\Desktop\code\src\vue-pages\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\index.js:6:21)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\work\Desktop\code\src\vue-pages\node_modules\_babel-core@6.26.0@babel-core\lib\api\node.js:6:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

 @ multi ./build/dev-client ./src/pages/index/index_main.js

 error  in ./src/pages/login/login_main.js

Module build failed: Error: Cannot find module 'babel-runtime/core-js/get-iterator'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\work\Desktop\code\src\vue-pages\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\index.js:6:21)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\work\Desktop\code\src\vue-pages\node_modules\_babel-core@6.26.0@babel-core\lib\api\node.js:6:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

 @ multi ./build/dev-client ./src/pages/login/login_main.js

运行报错

**Comment by zhuss** [comment]
恩 可能是依赖版本有问题吧，不知道你有没有试过yarn，如果可以，你试一下。

**Comment by wenghaoping** [comment]
用你的demo可以运行，也很好，但是我用的是新的vue-cli，有些地方配置不同，我大致都修改成和你的一样，但是报错
![image](https://user-images.githubusercontent.com/21232705/34190852-13fdf178-e57e-11e7-880d-d8beacb3190f.png)
这个我就很无奈了，不知道可以帮忙看下吗
